### ISSUE TITLE
Update Announcement Section

### ISSUE THREAD

**Issue by ravichanga101** [ravichanga101/CHARUSATv4#13]
update Dan Bhasker Award

The "Lokarpan" of the Late Shri Dahyabhai Fulabhai Patel & Late Shri Ishwarbhai Fulabhai Patel (Palaj)-Department of Dental Care @ CHARUSAT Hospital and the Presentation of Daan Bhaskar Award to Shri Jigar Ashokbhai Patel, Prominent Hostelier, USA and Esteemed Donor, CHARUSAT Hospital is scheduled on 25th January, 2024 from 10.30 a.m. onwards.  The Invitation card is attached herewith.

**Comment by Nirmalchaudhary** [comment]
updated
